### ISSUE TITLE
Multi-threading does not work (Qt 5.13.1, OSG 3.6.4, MSVC 2019 x64, Win10)

### ISSUE THREAD

**Issue by villains** [openscenegraph/osgQt#30]
Latest revision of osgQt (rev hash 2153914faf422403d0e3b4e2e15bceaaf4ef0d9b) has been built and installed. The osgviewerQt example works fine.

I wanted to try out the multi-threaded modes to increase performance. However, it does not work.

For example, switching the viewer to `ThreadPerCamera` results in a continuous slew of error and warning messages on stdout, and the `osgQOpenGLWidget` appears in solid black colour.

Example of warnings and errors:

```
Error: OpenGL version test failed, requires valid graphics context.
Warning: detected OpenGL error 'invalid operation' at Before Renderer::compile
Warning: detected OpenGL error 'invalid operation' at After Renderer::compile
Warning: detected OpenGL error 'invalid operation' at after RenderBin::draw(..)
Warning: detected OpenGL error 'invalid operation' at end of SceneView::draw()
Warning: detected OpenGL error 'invalid operation' after applying attribute Viewport 000001C17B38D790
Warning: detected OpenGL error 'invalid operation' after applying GLMode 0xc11
Warning: detected OpenGL error 'invalid operation' after applying GLMode 0xc11
Warning: detected OpenGL error 'invalid operation' after applying attribute Viewport 000001C17BDAAB60
```

The block of warnings following the initial error message repeats over and over again. Presumably these warnings occur each time OSG attempts to draw a frame.

These errors and warnings do not appear if I leave `SingleThreaded` mode enabled.

What should I do to get multi-threaded rendering to work?

This is important because I plan to have multiple OSG views in a Qt app, each visualizing its own separate OSG scene graph. I am anticipating performance problems if everything (Qt GUI, OSG processing and rendering) were done from a single thread. Multi-threading would be important even if the only reason was to keep the GUI responsive.

Any thoughts?
Thank you.

**Comment by mathieu** [comment]
Hi, Qt's openGL implementation needs to render from main thread. OSG's multithread starts multi-threading from the main thread into render Threads. These are not reconcilable...

**Comment by villains** [comment]
Hmm. That sucks. So there is absolutely no way to get multi-threaded OSG rendering with Qt?

**Comment by villains** [comment]
Is there a way to get the other operations (update and cull) to happen in other threads, keeping only the OpenGL drawing in the main thread?

**Comment by mathieu** [comment]
Sorry, but without refactoring osg there is no way it can be done. And refactoring osg is what got osgQt kick out from main osg repo.

**Comment by mathieu** [comment]
no problem, I needed this feature also but Qt's modern OpenGL handling makes this impossible without some refactoring either in Qt or in OSG...

**Comment by sdh4** [comment]
Correct me if I'm wrong but the needed refactoring under discussion is related to the Viewer class, parallelization of a render process, and the need to configure the automatically-generated threads with suitable contexts for rendering in the QT environment? 

It looks like in certain applications a partially threaded render might be possible: Render to texture framebuffer(s) in a separate thread using a separate QT-created context  and QT's makeCurrent() and doneCurrent() methods to do the context swaps. 

Then the main QT thread can blit/compose/3D render from the texture framebuffers into the actual window. Does this sound plausible? It would at least prevent slow rendering from bogging down the main GUI thread. 

The biggest potential pitfall I can think of would be the texture framebuffers not being available (because they are being redrawn) at an instant where the main QT thread wants a redraw. But I would imagine that just ignoring the paintGL() in that circumstance would recompose based on the prior output. 

Make sense? Seem plausible?
