### ISSUE TITLE
More infos about this project

### ISSUE THREAD

**Issue by gambr** [openscenegraph/osgQt#33]
Hi,
I worked with OSG 3.4.0 where osgQt was included.
Now I want to move to OSG 3.6.4 and realized osgQt has been removed. I found this project, and I can understand it comes from the osgQt library that was part of OSG in the past.

Which is the OSG version supported? Which version of Qt is supported? Could you please add those infos in every tag, branch, release so that it is clear?

Best regards,
Gianni

**Comment by CJCombrink** [comment]
I would also really like to know why this library was removed. 
For example if it was removed because there are no maintainers or support from the main OSG it might be relevant to people to make it clear that this library will get out of sync with main OSG at some point (soon) thus consider alternatives on new projects.

**Comment by openscenegraph** [comment]
On Mon, 9 Dec 2019 at 13:32, Carel <notifications@github.com> wrote:

> I would also really like to know why this library was removed.
> For example if it was removed because there are no maintainers or support
> from the main OSG it might be relevant to people to make it clear that this
> library will get out of sync with main OSG at some point (soon) thus
> consider alternatives on new projects.
>
I had to remove osgQt as it had long become impractical for me to
personally maintain it as part of the core OSG. For quite a few OSG stable
releases it had been a serious issue trying to get it tested and ready for
release along with the rest of the OSG, all the different versions of Qt
compounded this problem.  I am not a Qt user and don't have expertise with
it. Without any expertise I can't provide guidance on how to use it, how to
fix bugs, but because it was part of the core OSG it kept falling at my
feet handle the support for it.

Given this experience trying to maintain the osgQt it should never have
been merged with the core OSG in the first place, so now moving it out of
the core places it where it should have been all along. Moving osgQt out of
the core allows it to be maintained by those on the OSG community that use
Qt and have expertise with it.  It allows osgQt to be track different
versions of Qt independently of the OSG versions.

Now, it's up to osgQt maintainers to keep it maintained.  If they no longer
feel that can manage this then I would suggest other members of the OSG/Qt
community step forward and pick up the reigns.

If the community OSG/Qt want to propose some new maintainers I can add
their github accounts to those that have write access to the osgQt
repository.

Cheers,
Robert.

**Comment by mathieu** [comment]
osgQt was tied to Qt4 in the 3.4 osg repository. Once extracted to this repo the compatibility was retained on Qt4 on a `topic/Qt4` branch

The master branch is based on Qt5 (and the new way of handling OpenGL) and is compatible with the osg 3.6 branch
